### ISSUE TITLE
Issues on M1

### ISSUE THREAD

**Issue by matthew-kerle** [adoptoposs/mjml_nif#45]
I am having issues getting this library to work on an M1 Mac. Any ideas on what we need to do to resolve this?

```
[warning] The on_load function for module Elixir.Mjml returned:
{:error,
 {:load_failed,
  'Failed to load NIF library: \'dlopen(/repo/_build/dev/lib/mjml/priv/native/libmjml_nif.so, 0x0002): tried: \'/Repo/_build/dev/lib/mjml/priv/native/libmjml_nif.so\' (mach-o file, but is an incompatible architecture (have \'x86_64\', need \'arm64e\')), \'/usr/local/lib/libmjml_nif.so\' (no such file), \'/usr/lib/libmjml_nif.so\' (no such file), \'/Repo/deps/mjml/priv/native/libmjml_nif.so\' (mach-o file, but is an incompatible architecture (have \'x86_64\', need \'arm64e\')), \'/usr/local/lib/libmjml_nif.so\' (no such file), \'/usr/lib/libmjml_nif.so\' (no such file)\''}}

[warning] The on_load function for module Elixir.Mjml returned:
{:error,
 {:load_failed,
  'Failed to load NIF library: \'dlopen(/Repo/_build/dev/lib/mjml/priv/native/libmjml_nif.so, 0x0002): tried: \'/Repo/_build/dev/lib/mjml/priv/native/libmjml_nif.so\' (mach-o file, but is an incompatible architecture (have \'x86_64\', need \'arm64e\')), \'/usr/local/lib/libmjml_nif.so\' (no such file), \'/usr/lib/libmjml_nif.so\' (no such file), \'/Repo/deps/mjml/priv/native/libmjml_nif.so\' (mach-o file, but is an incompatible architecture (have \'x86_64\', need \'arm64e\')), \'/usr/local/lib/libmjml_nif.so\' (no such file), \'/usr/lib/libmjml_nif.so\' (no such file)\''}}
```

**Comment by paulgoetze** [comment]
Hey @matthew-kerle, thank you for opening this issue. 

It seems like for some reason you have the mjml_nif.so compiled for the wrong architecture ("x86_64 instead of arm64e" in your error message).

Unfortunately I don't have an M1 at hand right now, so I cannot check exactly what might be the issue. 

The only thing I could find is a similar issue with multiple Rust installations on the same machine, which led to a similar error message:
https://github.com/tzumby/ex_keccak/issues/21

Here, reinstalling Rust seemed to have fixed the issue.

In case it doesn't for you: What's the Erlang/Elixir + Rust version you're working with?

**Comment by matthew-kerle** [comment]
@paulgoetze thanks for the response -- I'll test a few things out tonight and give you some more details if that doesn't resolve it.

**Comment by matthew-kerle** [comment]
@paulgoetze re-installing Rust seemed to work for me, thank you!
